{{/* @formatter:off */}}
{{- if .Values.ingress.aadAuthentication -}}
{{- $fullname := include "project.fullname" . -}}
{{- $host := include "project.tls.host" . -}}
{{- $proxyname := include "project.oauthproxyname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $proxyname }}
data:
  OAUTH2_PROXY_CLIENT_ID: {{ required "clientId is required" .Values.ingress.aad.clientId }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ required "clientSecret is required" .Values.ingress.aad.clientSecret }}
  OAUTH2_PROXY_COOKIE_DOMAINS: "{{ $host }}"
  OAUTH2_PROXY_COOKIE_SECRET: {{ randAlphaNum 16 | b64enc }}
  OAUTH2_PROXY_EMAIL_DOMAINS: {{ default "*" .Values.ingress.aad.emailDomain | quote }}
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/{{ .Values.ingress.aad.tenantId }}/v2.0"
  OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
  OAUTH2_PROXY_PASS_USER_HEADERS: "true"
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://localhost:6379
  OAUTH2_PROXY_SESSION_STORE_TYPE: redis
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_UPSTREAM: "http://{{ $fullname }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
  OAUTH2_PROXY_USER_ID_CLAIM: "preferred_username"
  OAUTH2_PROXY_WHITELIST_DOMAINS: "{{ $host }}"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
{{- end -}}
