{{/* @formatter:off */}}
{{- if .Values.ingress.aadAuthentication -}}
{{- $fullname := include "project.fullname" . -}}
{{- $proxyname := include "project.oauthproxyname" . -}}
{{- $host := include "project.tls.host" . -}}
{{- $baseDomain := include "project.baseDomain" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $proxyname }}
  labels: {{ include "project.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $proxyname }}
              servicePort: http
            path: /oauth2
  tls:
    - hosts:
      - {{ $host | quote }}
      secretName: "{{ $host | replace "." "-" }}-ingress-cert"
{{- end -}}
